#!/bin/sh
set -eu

cd "${0%/*}" || exit 1

if [ -z "${WM_PROJECT_DIR:-}" ]; then
    echo "OpenFOAM environment is not loaded. Source OpenFOAM-14/etc/bashrc first." >&2
    exit 1
fi

build_lib()
{
    dir=$1
    shift
    echo "==> Building $dir"
    (cd "$dir" && wmake "$@" libso)
}

build_lib thermophysicalModels/flameletExtraction/common "$@"
build_lib thermophysicalModels/flameletExtraction/flamelets/turbulent "$@"
build_lib thermophysicalModels/basic "$@"
build_lib applications/solvers/combustion/SLFMFluid "$@"

echo "OF14 flamelet libraries and SLFMFluid module built."
