#!/bin/sh
set -eu

cd "${0%/*}" || exit 1

clean_lib()
{
    dir=$1
    echo "==> Cleaning $dir"
    (cd "$dir" && wclean libso)
}

clean_lib applications/solvers/combustion/SLFMFluid
clean_lib thermophysicalModels/basic
clean_lib thermophysicalModels/flameletExtraction/flamelets/turbulent
clean_lib thermophysicalModels/flameletExtraction/common
